### ISSUE TITLE
large number of recipes exceeds the packet size

### ISSUE THREAD

**Issue by Linguardium** [cakewhip/tcrafting#2]
```
Caused by: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.toPacket(ServerSidePacketRegistryImpl.java:91) ~[c0ec2da0-361b-461a-8266-5677a104e82d.jar:?]
	at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:72) ~[c0ec2da0-361b-461a-8266-5677a104e82d.jar:?]
	at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:93) ~[c0ec2da0-361b-461a-8266-5677a104e82d.jar:?]
	at com.kqp.tcrafting.network.base.BasePacketS2C.sendToPlayer(BasePacketS2C.java:15) ~[tcrafting-mc1.16.1-v1.1.1.jar:?]
	at com.kqp.tcrafting.network.base.BasePacketS2C.sendToPlayer(BasePacketS2C.java:22) ~[tcrafting-mc1.16.1-v1.1.1.jar:?]
	at com.kqp.tcrafting.network.recipe.SyncRecipeManagerS2C.sendToPlayer(SyncRecipeManagerS2C.java:25) ~[tcrafting-mc1.16.1-v1.1.1.jar:?]
	at net.minecraft.class_3324.handler$zdk001$onPlayerConnect(class_3324.java:1945) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:270) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:111) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:63) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:229) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:170) ~[intermediary-minecraft-1.16.1-client.jar:?]
	... 6 more```

seems to occur when there are many recipes and tcrafting attempts to sync them all

**Comment by cakewhip** [comment]
Somehow missed this issue, but this has been fixed as of v1.2.0
